/**
 * Copyright (C) 2013 Julian Atienza Herrero <j.atienza at har.mrc.ac.uk>
 *
 * MEDICAL RESEARCH COUNCIL UK MRC
 *
 * Harwell Mammalian Genetics Unit
 *
 * http://www.har.mrc.ac.uk
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.08 at 09:05:55 AM BST 
//


package org.mousephenotype.dcc.exportlibrary.datastructure.tracker.validation_report;

import org.mousephenotype.dcc.exportlibrary.datastructure.tracker.validation_report.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="validationReport" type="{http://www.mousephenotype.org/dcc/exportlibrary/datastructure/tracker/validation_report}ValidationReport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validationReport"
})
@XmlRootElement(name = "validationReportSet")
@Entity(name = "ValidationReportSet")
@Table(name = "VALIDATIONREPORTSET")
@Inheritance(strategy = InheritanceType.JOINED)
public class ValidationReportSet
    implements Serializable, Equals, HashCode
{

    @XmlElement(required = true)
    protected List<ValidationReport> validationReport;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the validationReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validationReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidationReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidationReport }
     * 
     * 
     */
    @OneToMany(targetEntity = ValidationReport.class, cascade = {
        CascadeType.ALL
    }, orphanRemoval = true)
    @JoinColumn(name = "VALIDATIONREPORT_VALIDATIONR_0")
    @OrderColumn(name = "VALIDATIONREPORT_HJORDER")
    public List<ValidationReport> getValidationReport() {
        if (validationReport == null) {
            validationReport = new ArrayList<ValidationReport>();
        }
        return this.validationReport;
    }

    /**
     * 
     * 
     */
    public void setValidationReport(List<ValidationReport> validationReport) {
        this.validationReport = validationReport;
    }

    @Transient
    public boolean isSetValidationReport() {
        return ((this.validationReport!= null)&&(!this.validationReport.isEmpty()));
    }

    public void unsetValidationReport() {
        this.validationReport = null;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ValidationReportSet)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ValidationReportSet that = ((ValidationReportSet) object);
        {
            List<ValidationReport> lhsValidationReport;
            lhsValidationReport = (this.isSetValidationReport()?this.getValidationReport():null);
            List<ValidationReport> rhsValidationReport;
            rhsValidationReport = (that.isSetValidationReport()?that.getValidationReport():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "validationReport", lhsValidationReport), LocatorUtils.property(thatLocator, "validationReport", rhsValidationReport), lhsValidationReport, rhsValidationReport)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<ValidationReport> theValidationReport;
            theValidationReport = (this.isSetValidationReport()?this.getValidationReport():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "validationReport", theValidationReport), currentHashCode, theValidationReport);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
