SELECT IMPRESSPARAMETER.PARAMETERNAME, IMPRESSPARAMETER.PARAMETERKEY,
        IMPRESSPARAMETERINCREMENT.TYPE_, IMPRESSPARAMETERINCREMENT.UNIT, IMPRESSPARAMETERINCREMENT.STRING, IMPRESSPARAMETERINCREMENT.MIN_
        

FROM IMPRESSPARAMETER join phenodcc_xmlvalidationresources.IMPRESSPARAMETERINCREMENT on (IMPRESSPARAMETER.HJID = IMPRESSPARAMETERINCREMENT.IMPRESSPARAMETERINCREMENT_IM_0)


