SELECT IMPRESSPARAMETER.PARAMETERNAME, IMPRESSPARAMETER.PARAMETERKEY,
        IMPRESSPARAMETERINCREMENT.TYPE_, IMPRESSPARAMETERINCREMENT.UNIT, IMPRESSPARAMETERINCREMENT.STRING, IMPRESSPARAMETERINCREMENT.MIN_,
        IMPRESSPARAMETEROPTION.NAME_

FROM IMPRESSPARAMETER join phenodcc_xmlvalidationresources.IMPRESSPARAMETERINCREMENT on (IMPRESSPARAMETER.HJID = IMPRESSPARAMETERINCREMENT.IMPRESSPARAMETERINCREMENT_IM_0)

join phenodcc_xmlvalidationresources.IMPRESSPARAMETEROPTION on (IMPRESSPARAMETER.HJID = IMPRESSPARAMETEROPTION.IMPRESSPARAMETEROPTION_IMPRE_0)
