--
-- Copyright (C) 2013 Julian Atienza Herrero <j.atienza at har.mrc.ac.uk>
--
-- MEDICAL RESEARCH COUNCIL UK MRC
--
-- Harwell Mammalian Genetics Unit
--
-- http://www.har.mrc.ac.uk
--
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License. You may obtain a copy of
-- the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
-- License for the specific language governing permissions and limitations under
-- the License.
--

/*select VALIDATIONREPORT.REPORTIDENTIFIER, count(1)
from phenodcc_raw.VALIDATIONREPORT
--where not VALIDATIONREPORT.SUPERSEEDED
group by VALIDATIONREPORT.REPORTIDENTIFIER
having count(1) >1
order by VALIDATIONREPORT.REPORTIDENTIFIER
*/
SELECT VALIDATIONREPORT.HJID,
    VALIDATIONREPORT.REPORTIDENTIFIER,
    VALIDATIONREPORT.SUPERSEEDED,
    EXPERIMENT_VALIDATIONREPORT__0
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603';
/*
SELECT MAX(VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0) AS experimentHJID,
VALIDATIONREPORT.REPORTIDENTIFIER                    AS REPORTIDENTIFIER,
HJID as hjid
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0 IS NOT NULL
and
VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603'
GROUP BY VALIDATIONREPORT.REPORTIDENTIFIER
*/

select HJID, VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603';

SELECT MAX(VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0) AS experimentHJID,
            VALIDATIONREPORT.REPORTIDENTIFIER                    AS REPORTIDENTIFIER,
            HJID                                                 AS hjid
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603';


select *
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603';



SELECT fname,file_name, SUBMISSION.TRACKERID,VALIDATIONREPORT.*
FROM phenodcc_tracker.xml_file
JOIN phenodcc_tracker.zip_download        ON zip_download.id = xml_file.zip_id
JOIN phenodcc_tracker.file_source_has_zip ON zip_download.zf_id = file_source_has_zip.id
JOIN phenodcc_tracker.zip_action          ON file_source_has_zip.za_id = zip_action.id
JOIN phenodcc_tracker.zip_file            ON zip_action.zip_id = zip_file.id
JOIN phenodcc_raw.SUBMISSION      ON xml_file.id = SUBMISSION.TRACKERID
JOIN phenodcc_context.context     ON SUBMISSION.HJID = context.id
JOIN phenodcc_raw.CENTREPROCEDURE ON SUBMISSION.HJID = CENTREPROCEDURE.CENTREPROCEDURE_SUBMISSION_H_0
JOIN phenodcc_raw.EXPERIMENT      ON EXPERIMENT.EXPERIMENT_CENTREPROCEDURE_H_0 = CENTREPROCEDURE.HJID
join phenodcc_raw.VALIDATIONREPORT on EXPERIMENT_VALIDATIONREPORT__0 = EXPERIMENT.HJID
where VALIDATIONREPORT.REPORTIDENTIFIER= 'GMC_102_21615_30253603_1_30253603';
                                              102_21615_30253604_1_30253604


SELECT VALIDATIONREPORT.REPORTIDENTIFIER, COUNT(1)
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 IS NOT NULL
GROUP BY VALIDATIONREPORT.REPORTIDENTIFIER
HAVING COUNT(1) >10
ORDER BY COUNT(1);


SELECT *
FROM phenodcc_raw.VALIDATIONREPORT
where VALIDATIONREPORT.REPORTIDENTIFIER = 'H_B6NTAC-USA/588.7b_4988040';

SELECT *
FROM phenodcc_raw.VALIDATIONREPORT
where VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_30254296';

update phenodcc_raw.VALIDATIONREPORT
set VALIDATIONREPORT.SUPERSEEDED = true
where VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603';

update phenodcc_raw.VALIDATIONREPORT
set VALIDATIONREPORT.SUPERSEEDED = false
where VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0 = 250620;


update phenodcc_raw.VALIDATIONREPORT,
(select max(hjid) as mxx from  phenodcc_raw.VALIDATIONREPORT where  VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603') as inter
set VALIDATIONREPORT.SUPERSEEDED = false
where VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_102_21615_30253603_1_30253603'
and VALIDATIONREPORT.HJID = inter.mxx
