--
-- Copyright (C) 2013 Julian Atienza Herrero <j.atienza at har.mrc.ac.uk>
--
-- MEDICAL RESEARCH COUNCIL UK MRC
--
-- Harwell Mammalian Genetics Unit
--
-- http://www.har.mrc.ac.uk
--
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License. You may obtain a copy of
-- the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
-- License for the specific language governing permissions and limitations under
-- the License.
--
--
--FIRST YOU SEARCH FOR ENTITIES THAT HAVE BEEN RESUBMITTED
SELECT @DAYS_AGO := 40;
SELECT IF(VALIDATIONREPORT.CENTREPROCEDURE_VALIDATIONRE_0 IS NULL
AND VALIDATIONREPORT.CENTRESPECIMEN_VALIDATIONREP_0 IS NULL, "submission", IF (VALIDATIONREPORT.CENTREPROCEDURE_VALIDATIONRE_0 IS NOT NULL
AND VALIDATIONREPORT.LINE_VALIDATIONREPORT__0 IS NULL
AND HOUSING_VALIDATIONREPORT__0 IS NULL
AND VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0 IS NULL, "centreprocedure", IF (VALIDATIONREPORT.CENTRESPECIMEN_VALIDATIONREP_0 IS NOT NULL
AND VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 IS NULL,"centrespecimen", IF(VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 IS NOT NULL,"specimen", IF(HOUSING_VALIDATIONREPORT__0 IS NOT NULL
AND VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0 IS NULL,"housing", IF(LINE_VALIDATIONREPORT__0 IS NOT NULL
AND VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0 IS NULL,"line", IF(VALIDATIONREPORT.EXPERIMENT_VALIDATIONREPORT__0 IS NOT NULL,"experiment",""))))))) AS type,
    --
    VALIDATIONREPORT.REPORTIDENTIFIER,
    MIN(VALIDATIONREPORT.SUBMISSIONDATE) AS firstTimeSubmitted,
    MAX(VALIDATIONREPORT.SUBMISSIONDATE) AS lastTimeSubmitted,
    COUNT(1)                             AS timesSubmitted
FROM phenodcc_raw.VALIDATIONREPORT
LEFT JOIN SUBMISSION                   ON SUBMISSION.HJID = VALIDATIONREPORT.SUBMISSION_VALIDATIONREPORT__0
LEFT JOIN phenodcc_raw.CENTREPROCEDURE ON VALIDATIONREPORT.CENTREPROCEDURE_VALIDATIONRE_0 =CENTREPROCEDURE.HJID
LEFT JOIN phenodcc_raw.CENTRESPECIMEN  ON VALIDATIONREPORT.CENTRESPECIMEN_VALIDATIONREP_0 = CENTRESPECIMEN.HJID
WHERE DATE_SUB(CURDATE(),INTERVAL @DAYS_AGO DAY) <= DATE(VALIDATIONREPORT.SUBMISSIONDATE)
GROUP BY VALIDATIONREPORT.REPORTIDENTIFIER
HAVING COUNT(1) >1
ORDER BY VALIDATIONREPORT.HJID DESC;
--
--THEN YOU SEE WHAT HAS HAPPENDED TO THEM
--
SELECT SUBMISSION.TRACKERID,
VALIDATIONREPORT.SUBMISSIONDATE,
    VALIDATIONREPORT.REPORTIDENTIFIER,
    VALIDATIONREPORT.ISVALID,
    VALIDATIONREPORT.SUPERSEEDED,
    VALIDATION.MESSAGE
FROM VALIDATIONREPORT
LEFT JOIN phenodcc_raw.SUBMISSION                   ON SUBMISSION.HJID = VALIDATIONREPORT.SUBMISSION_VALIDATIONREPORT__0
LEFT JOIN phenodcc_raw.VALIDATION_REPORT_VALIDATION ON VALIDATIONREPORT.HJID = VALIDATION_REPORT_VALIDATION.validationreport
LEFT JOIN phenodcc_raw.VALIDATION                   ON VALIDATION.HJID = VALIDATION_REPORT_VALIDATION.validation
WHERE VALIDATIONREPORT.REPORTIDENTIFIER = 'GMC_166_22649_30262150_1_30262150';

    
    