--
-- Copyright (C) 2013 Julian Atienza Herrero <j.atienza at har.mrc.ac.uk>
--
-- MEDICAL RESEARCH COUNCIL UK MRC
--
-- Harwell Mammalian Genetics Unit
--
-- http://www.har.mrc.ac.uk
--
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License. You may obtain a copy of
-- the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
-- License for the specific language governing permissions and limitations under
-- the License.
--

SELECT concat(CENTRESPECIMEN.CENTREID,'_',SPECIMEN.SPECIMENID) AS reporterID
FROM phenodcc_raw.CENTRESPECIMEN
JOIN phenodcc_raw.SPECIMEN ON CENTRESPECIMEN.HJID = SPECIMEN.MOUSEOREMBRYO_CENTRESPECIMEN_0
WHERE concat(CENTRESPECIMEN.CENTREID,'_',SPECIMEN.SPECIMENID) NOT IN
    (SELECT VALIDATIONREPORT.REPORTIDENTIFIER
        FROM phenodcc_raw.VALIDATIONREPORT );

/*
specimen.hjid not in validation report	
1970508	J_C5409
1970530	J_C5628
1970532	J_C5631
1970534	J_C5633
1970548	J_C5676
1970550	J_C5678
1970552	J_C5681
1970554	J_C5684
1970556	J_C5686
*/

--
--
--
--
UPDATE VALIDATIONREPORT,
    (SELECT SPECIMEN.HJID                                           AS specimenHJID,
            concat(CENTRESPECIMEN.CENTREID,'_',SPECIMEN.SPECIMENID) AS reporterID,
            CENTRESPECIMEN.HJID                                     AS centreSpecimenHJID
        FROM phenodcc_raw.CENTRESPECIMEN
        JOIN phenodcc_raw.SPECIMEN   ON CENTRESPECIMEN.HJID = SPECIMEN.MOUSEOREMBRYO_CENTRESPECIMEN_0
        JOIN phenodcc_raw.VALIDATION ON SPECIMEN_VALIDATION_HJID = SPECIMEN.HJID
        ORDER BY SPECIMEN.HJID ) internal
SET VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = internal.specimenHJID
WHERE VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 IS NULL
AND internal.reporterID = VALIDATIONREPORT.REPORTIDENTIFIER
AND VALIDATIONREPORT.CENTRESPECIMEN_VALIDATIONREP_0 = internal.centreSpecimenHJID;
SELECT SPECIMEN.HJID,
    concat(CENTRESPECIMEN.CENTREID,'_',SPECIMEN.SPECIMENID) AS reporterID
FROM phenodcc_raw.CENTRESPECIMEN
JOIN phenodcc_raw.SPECIMEN ON CENTRESPECIMEN.HJID = SPECIMEN.MOUSEOREMBRYO_CENTRESPECIMEN_0
WHERE SPECIMEN.HJID NOT IN
    (SELECT SPECIMEN_VALIDATIONREPORT_HJ_0
        FROM phenodcc_raw.VALIDATIONREPORT
        WHERE SPECIMEN_VALIDATIONREPORT_HJ_0 IS NOT NULL)
ORDER BY reporterID;
--
--
SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5409' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970507;
--
--
update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970508
where VALIDATIONREPORT.HJID = 8626830;
--
--
SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5628' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970529;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970530
where VALIDATIONREPORT.HJID = 8626832;

--
--

SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5631' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970531;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970531
where VALIDATIONREPORT.HJID = 8626834;

--
--

SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5633' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970533;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970534
where VALIDATIONREPORT.HJID = 8626836;

--
--

SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5676' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970547;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970548
where VALIDATIONREPORT.HJID = 8626838;


--
--

SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5678' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970549;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970550
where VALIDATIONREPORT.HJID = 8626840;

--
--

SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5678' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970549;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970550
where VALIDATIONREPORT.HJID = 8626840;

--
--

SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5681' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970551;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970552
where VALIDATIONREPORT.HJID = 8626842;

--
--


SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5684' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970553;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970554
where VALIDATIONREPORT.HJID = 8626844;

--
--
SELECT HJID
FROM phenodcc_raw.VALIDATIONREPORT
WHERE VALIDATIONREPORT.REPORTIDENTIFIER ='J_C5686' and VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970555;

update phenodcc_raw.VALIDATIONREPORT

set VALIDATIONREPORT.SPECIMEN_VALIDATIONREPORT_HJ_0 = 1970556
where VALIDATIONREPORT.HJID = 8626846;