--
-- Copyright (C) 2013 Julian Atienza Herrero <j.atienza at har.mrc.ac.uk>
--
-- MEDICAL RESEARCH COUNCIL UK MRC
--
-- Harwell Mammalian Genetics Unit
--
-- http://www.har.mrc.ac.uk
--
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License. You may obtain a copy of
-- the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
-- License for the specific language governing permissions and limitations under
-- the License.
--

USE phenodcc_raw;
SET @@foreign_key_checks = 0;
DROP TABLE
    VALIDATIONREPORT;
CREATE TABLE
    VALIDATIONREPORT
    (
        HJID bigint NOT NULL,
        DURATION bigint,
        ISVALID BOOLEAN,
        PHASE VARCHAR(255),
        REPORTIDENTIFIER VARCHAR(255),
        STATUS VARCHAR(255),
        SUBMISSIONDATE DATETIME,
        SUPERSEEDED BOOLEAN,
        CENTREPROCEDURE_VALIDATIONRE_0 bigint,
        CENTRESPECIMEN_VALIDATIONREP_0 bigint,
        EXPERIMENT_VALIDATIONREPORT__0 bigint,
        RESOURCEVERSION_VALIDATIONRE_0 bigint,
        SPECIMEN_VALIDATIONREPORT_HJ_0 bigint,
        SUBMISSION_VALIDATIONREPORT__0 bigint,
        VALIDATIONREPORT_VALIDATIONR_0 bigint,
        PRIMARY KEY (HJID)
    )
    ENGINE=InnoDB;
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EEDC92C1AAA (CENTRESPECIMEN_VALIDATIONREP_0),
    ADD CONSTRAINT FKAE4B7EEDC92C1AAA FOREIGN KEY (CENTRESPECIMEN_VALIDATIONREP_0) REFERENCES
    CENTRESPECIMEN (HJID);
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EED773A66CC (VALIDATIONREPORT_VALIDATIONR_0),
    ADD CONSTRAINT FKAE4B7EED773A66CC FOREIGN KEY (VALIDATIONREPORT_VALIDATIONR_0) REFERENCES
    VALIDATIONREPORTSET (HJID);
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EED24F78B5B (RESOURCEVERSION_VALIDATIONRE_0),
    ADD CONSTRAINT FKAE4B7EED24F78B5B FOREIGN KEY (RESOURCEVERSION_VALIDATIONRE_0) REFERENCES
    RESOURCEVERSION (HJID);
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EEDDE45AC71 (SUBMISSION_VALIDATIONREPORT__0),
    ADD CONSTRAINT FKAE4B7EEDDE45AC71 FOREIGN KEY (SUBMISSION_VALIDATIONREPORT__0) REFERENCES
    SUBMISSION (HJID);
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EED7E9598A4 (SPECIMEN_VALIDATIONREPORT_HJ_0),
    ADD CONSTRAINT FKAE4B7EED7E9598A4 FOREIGN KEY (SPECIMEN_VALIDATIONREPORT_HJ_0) REFERENCES
    SPECIMEN (HJID);
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EEDBB75FFE9 (CENTREPROCEDURE_VALIDATIONRE_0),
    ADD CONSTRAINT FKAE4B7EEDBB75FFE9 FOREIGN KEY (CENTREPROCEDURE_VALIDATIONRE_0) REFERENCES
    CENTREPROCEDURE (HJID);
ALTER TABLE
    VALIDATIONREPORT ADD INDEX FKAE4B7EEDDEFDF711 (EXPERIMENT_VALIDATIONREPORT__0),
    ADD CONSTRAINT FKAE4B7EEDDEFDF711 FOREIGN KEY (EXPERIMENT_VALIDATIONREPORT__0) REFERENCES
    EXPERIMENT (HJID);
CREATE INDEX
    reportIdentifierIndex
ON
    VALIDATIONREPORT
    (
        REPORTIDENTIFIER
    );
CREATE INDEX
    experimentIDIndex
ON
    EXPERIMENT
    (
        EXPERIMENTID
    );
CREATE INDEX
    specimenIDIndex
ON
    SPECIMEN
    (
        SPECIMENID
    );
CREATE INDEX
    strainIDIndex
ON
    SPECIMEN
    (
        STRAINID
    );
CREATE INDEX
    colonyIDIndex
ON
    SPECIMEN
    (
        COLONYID
    );
CREATE TABLE
    RESOURCEVERSION
    (
        HJID bigint NOT NULL,
        IMPRESSVERSION VARCHAR(255),
        MGIDOWNLOAD DATETIME,
        PRIMARY KEY (HJID)
    )
    ENGINE=InnoDB;
    
UPDATE
    phenodcc_raw.SPECIMEN
SET
    SPECIMEN.PRODUCTIONCENTRE = 'BCM'
WHERE
    SPECIMEN.PRODUCTIONCENTRE = 'BAY';

UPDATE
    phenodcc_raw.SPECIMEN
SET
    SPECIMEN.PRODUCTIONCENTRE = 'TCP'
WHERE
    SPECIMEN.PRODUCTIONCENTRE = 'NCOM';
    
    
UPDATE
    phenodcc_raw.SPECIMEN
SET
    SPECIMEN.PRODUCTIONCENTRE = 'GMC'
WHERE
    SPECIMEN.PRODUCTIONCENTRE = 'HMGU';    

UPDATE
    phenodcc_raw.SPECIMEN
SET
    SPECIMEN.PHENOTYPINGCENTRE = 'TCP'
WHERE
    SPECIMEN.PHENOTYPINGCENTRE= 'NCOM';
    

UPDATE
    phenodcc_raw.SPECIMEN
SET
    SPECIMEN.PHENOTYPINGCENTRE = 'BCM'
WHERE
    SPECIMEN.PHENOTYPINGCENTRE= 'BAY';
    


UPDATE
    phenodcc_raw.SPECIMEN
SET
    SPECIMEN.PHENOTYPINGCENTRE = 'GMC'
WHERE
    SPECIMEN.PHENOTYPINGCENTRE= 'HMGU';
    

    

UPDATE
    phenodcc_raw.CENTREPROCEDURE
SET
    CENTREPROCEDURE.CENTREID = 'TCP'
WHERE
    CENTREPROCEDURE.CENTREID = 'NCOM';
    

UPDATE
    phenodcc_raw.CENTREPROCEDURE
SET
    CENTREPROCEDURE.CENTREID = 'BCM'
WHERE
    CENTREPROCEDURE.CENTREID = 'BAY';
    
    UPDATE
    phenodcc_raw.CENTREPROCEDURE
SET
    CENTREPROCEDURE.CENTREID = 'GMC'
WHERE
    CENTREPROCEDURE.CENTREID = 'HMGU';
    
    
UPDATE
    phenodcc_raw.CENTRESPECIMEN
SET
    CENTRESPECIMEN.CENTREID = 'TCP'
WHERE
    CENTRESPECIMEN.CENTREID = 'NCOM';
SET @@foreign_key_checks = 1;

    
UPDATE
    phenodcc_raw.CENTRESPECIMEN
SET
    CENTRESPECIMEN.CENTREID = 'BCM'
WHERE
    CENTRESPECIMEN.CENTREID = 'BAY';
SET @@foreign_key_checks = 1;

    
UPDATE
    phenodcc_raw.CENTRESPECIMEN
SET
    CENTRESPECIMEN.CENTREID = 'GMC'
WHERE
    CENTRESPECIMEN.CENTREID = 'HMGU';
    
SET @@foreign_key_checks = 1;